package me.dszopa.website.repo;

import me.dszopa.website.entity.PokemonTeam;
import org.springframework.data.jpa.repository.JpaRepository;

import org.springframework.transaction.annotation.Transactional;

/**
 * Created by dszopa on 1/15/16.
 */
@Transactional
public interface PokemonTeamRepo extends JpaRepository<PokemonTeam, Long> {

    /**
     * No need for implementation because its autogenerated
     */
}
